# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample2 <- function(x, N) {
    .Call('RDbootstraps_sample2', PACKAGE = 'RDbootstraps', x, N)
}

poly2 <- function(x, r) {
    .Call('RDbootstraps_poly2', PACKAGE = 'RDbootstraps', x, r)
}

lpreg1 <- function(X, W, y) {
    .Call('RDbootstraps_lpreg1', PACKAGE = 'RDbootstraps', X, W, y)
}

lpreg2 <- function(X, W, y) {
    .Call('RDbootstraps_lpreg2', PACKAGE = 'RDbootstraps', X, W, y)
}

srd <- function(yxwl, yxwr, r) {
    .Call('RDbootstraps_srd', PACKAGE = 'RDbootstraps', yxwl, yxwr, r)
}

srdsampling <- function(yres, w, Nbc) {
    .Call('RDbootstraps_srdsampling', PACKAGE = 'RDbootstraps', yres, w, Nbc)
}

srdbc <- function(yxwl, yxwr, Nbc, p, q, dist) {
    .Call('RDbootstraps_srdbc', PACKAGE = 'RDbootstraps', yxwl, yxwr, Nbc, p, q, dist)
}

srdbcboot <- function(yxwl, yxwr, Nbc, Nci, p, q) {
    .Call('RDbootstraps_srdbcboot', PACKAGE = 'RDbootstraps', yxwl, yxwr, Nbc, Nci, p, q)
}

