// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sample2
arma::vec sample2(arma::vec x, int N);
RcppExport SEXP RDbootstraps_sample2(SEXP xSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    __result = Rcpp::wrap(sample2(x, N));
    return __result;
END_RCPP
}
// poly2
arma::mat poly2(arma::vec x, int r);
RcppExport SEXP RDbootstraps_poly2(SEXP xSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    __result = Rcpp::wrap(poly2(x, r));
    return __result;
END_RCPP
}
// lpreg1
double lpreg1(arma::mat X, arma::mat W, arma::vec y);
RcppExport SEXP RDbootstraps_lpreg1(SEXP XSEXP, SEXP WSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    __result = Rcpp::wrap(lpreg1(X, W, y));
    return __result;
END_RCPP
}
// lpreg2
arma::mat lpreg2(arma::mat X, arma::mat W, arma::vec y);
RcppExport SEXP RDbootstraps_lpreg2(SEXP XSEXP, SEXP WSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    __result = Rcpp::wrap(lpreg2(X, W, y));
    return __result;
END_RCPP
}
// srd
double srd(arma::mat yxwl, arma::mat yxwr, int r);
RcppExport SEXP RDbootstraps_srd(SEXP yxwlSEXP, SEXP yxwrSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type yxwl(yxwlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yxwr(yxwrSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    __result = Rcpp::wrap(srd(yxwl, yxwr, r));
    return __result;
END_RCPP
}
// srdsampling
arma::mat srdsampling(arma::vec yres, arma::vec w, int Nbc);
RcppExport SEXP RDbootstraps_srdsampling(SEXP yresSEXP, SEXP wSEXP, SEXP NbcSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type Nbc(NbcSEXP);
    __result = Rcpp::wrap(srdsampling(yres, w, Nbc));
    return __result;
END_RCPP
}
// srdbc
arma::vec srdbc(arma::mat yxwl, arma::mat yxwr, int Nbc, int p, int q, int dist);
RcppExport SEXP RDbootstraps_srdbc(SEXP yxwlSEXP, SEXP yxwrSEXP, SEXP NbcSEXP, SEXP pSEXP, SEXP qSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type yxwl(yxwlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yxwr(yxwrSEXP);
    Rcpp::traits::input_parameter< int >::type Nbc(NbcSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type dist(distSEXP);
    __result = Rcpp::wrap(srdbc(yxwl, yxwr, Nbc, p, q, dist));
    return __result;
END_RCPP
}
// srdbcboot
arma::vec srdbcboot(arma::mat yxwl, arma::mat yxwr, int Nbc, int Nci, int p, int q);
RcppExport SEXP RDbootstraps_srdbcboot(SEXP yxwlSEXP, SEXP yxwrSEXP, SEXP NbcSEXP, SEXP NciSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type yxwl(yxwlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yxwr(yxwrSEXP);
    Rcpp::traits::input_parameter< int >::type Nbc(NbcSEXP);
    Rcpp::traits::input_parameter< int >::type Nci(NciSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    __result = Rcpp::wrap(srdbcboot(yxwl, yxwr, Nbc, Nci, p, q));
    return __result;
END_RCPP
}
